[package]
name = "rustpad"
version = "0.1.0"
authors = ["joshua salzedo <thHunkn0WNd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.7.4"
toml = "0.5.6"
serde = "1.0.110"
serde_derive = "1.0.110"
